=== Functions and properties

==== Functions

Kotlin functions are declared using ``fun``:

[source,kotlin]
----
fun functionName(params): Type {...}
----

Parameters, along with all other values in Kotlin, are defined using _Pascal notation_.
Parameters can also have _default arguments_, which helps to reduce the need for overloads.

[source,kotlin]
----
fun makePurchase(amount: Int = 1) {
    ...
}
----

If no return type is specified, it is inferred to be ``Unit``.
Similarly, if a ``return`` statement is made with no value, it will implicitly return ``Unit``:

[source,kotlin]
----
fun foo() { // Equivalent to fun foo(): Unit
    return // return Unit
}
----

If no return statement is present in the body of a function, and the function is specified to return ``Unit``, it is implicitly returned.

If a function's body consists of a single expression, you can make use of a special, shorter syntax:

[source,kotlin]
----
override fun toString() = "..."
----

Single-expression functions can have their return types omitted; they will be inferred from the expression.

===== Variadic arguments

A parameter can accept an arbitrary number of arguments if it is annotated by ``varargs``:

[source,kotlin]
----
fun takeLotsOfStrings(vararg strings: String) {
    for (string in strings) println(string)
}
----

Within the function, ``varargs`` parameters are treated as arrays and can be used as such.

To pass the contents of an array to a ``varargs`` parameter, you can use the _spread operator_ ``*``:

[source,kotlin]
----
val strings = arrayOf("Hello", "world")
// The spread operator can even interleave varargs parameters!
takeLotsOfStrings("Something", *strings, "else")
----

CAUTION: No more than one parameter per function can be ``varargs``.

===== Named arguments

When invoking a function, parameters can be referred to by name.
This is helpful when invoking a function with multiple default parameter values:

[source,kotlin]
----
fun joinToString(
    strings: Iterable<String>,
    separator: CharSequence = ", ",
    prefix: CharSequence = "",
    postfix: CharSequence = "",
    limit: Int = -1,
    truncated: CharSequence = "...",
    transform: ((T) -> CharSequence)? = null
): String { ... }

...

joinToString(listOf("Hello", "world"), separator = "; ", truncated = " (more)")
----

If named arguments had not been used, redundant values for all intermediate parameters would have had to have been specified.

===== Extension functions

It is possible to define _extension functions_ for external classes.
Unlike C#, there is no requirement that they be placed in a "static class"; they are typically placed at the top level.

[source,kotlin]
----
fun Float.inverse(): Float {
    return 1 / this
}

print((3.0f).inverse()) // 0.33333334
----

Within an extension function, ``this`` refers to the receiver.

NOTE: Extension functions can have nullable receivers! This is why you can call ``toString`` on a ``null`` value -- ``toString`` is a standard extension function defined as ``Any?.toString(): String``.

==== Properties

Kotlin, like Swift, has no concept of _fields_.
All instance attributes are automatically encapsulated in properties.

Properties may be backed by fields internally; this is the default.
They may also have custom accessors.

The syntax for defining a property is:

[source,kotlin]
----
[var/val] name: Type = [initialValue]
    get
    set
----

This notation, where the type follows the name, is called _Pascal notation_.

``var`` properties are _mutable_; they have getters and setters, whereas ``val`` properties only have getters.
By default, the getter and setter can be omitted, unless you wish to apply an access modifier or annotation to it.

[source,kotlin]
----
var property: Any? = null
    @Inject internal set
----

Getters and setters may also have bodies, as in C#:

[source,kotlin]
----
var fullName: String
    get() {
        return "$first $last"
    }
    set(value) {
        val split = value.split(" ")
        first = split[0]
        last = split.skip(1).joinToString(" ")
    }
----

If the body of a getter or setter contains a single expression, the braces may be omitted similarly to functions:

[source,kotlin]
----
val fullName: String
    get() = "$first $last"
----

The type of the property may usually be omitted; it will be automatically inferred from its getter or initial value.

[source,kotlin]
----
// These are equivalent:
val foo: Int = 3
val foo = 3
----

===== Backing fields

Within the body of a field-backed property's getter or setter, a **magic variable** called ``field`` is accessible.
This is a mutable reference to the property's backing field, and can be used to easily add additional logic to a property setter.

Without ``lateinit``, the property would have to be declared as nullable because its initial value is ``null``; every operation on it would either have to make use of the ``!!`` operator or use unnecessary ``?.`` chaining.

[source,kotlin]
----
var positiveInt: Int = 1
    get
    set(value) {
        if (value > 0) field = value
    }
----

NOTE: If a property is not given an initial value, or if ``field`` is never used, the property will not have a backing field; it is purely compiled to a getter (and a setter, if the property is a ``var``).
This is useful for creating e.g. "compound properties" (like the aforementioned ``fullName``) that should not be stored in memory and are the result of performing cheap operations.

TIP: Properties with no backing field
https://kotlinlang.org/docs/reference/inline-functions.html#inline-properties[can be declared as ``inline``]; no getters or setters will be generated, as they will be inlined into the calling code.

===== ``lateinit`` properties

The ``lateinit`` modifier allows a property or local variable of a non-nullable type to initially have no value.
This is especially useful for classes that do not have their fields initialized at construction time; Android activities, test fixtures, or Spring services are common examples.

[source,kotlin]
----
@Test
class FooServiceTest {
    lateinit var fooService: FooService

    @BeforeClass
    fun init() {
        this.fooService = ...
    }
}
----

===== Extension properties

It is also possible to define _extension properties_ that act identically to extension functions:

[source,kotlin]
----
val Float.integerPart: Float get() = this.toInt().toFloat()

print((2.6543f).integerPart) // 2.0
----

==== Nesting

===== Local functions and classes

Classes and functions can be declared _locally_, that is, within other functions:

[source,kotlin]
----
fun foo() {
    fun bar() {
        ...
    }
    class Quux

    bar()
}

fun baz() {
    bar() // ERROR
    Quux::class // ERROR
}
----

This is an invaluable tool -- the scope of symbols should be restricted as much as possible, and if a certain subroutine or data class is only needed within a function, it is a great idea to make them local to that function.

=== Classes, functions, properties, and inheritance

Kotlin classes, functions and properties are ``final`` by default.
They can be made virtual by adding the ``open`` modifier:

[source,kotlin]
----
open class Foo // This class can be extended!
----

Abstract classes and functions do not need to be declared as ``open``, as this would defeat their purpose.

==== Inheritance

To extend a class, add it after the type name using the C++-style extension syntax:

[source,kotlin]
----
class Derived : Base
----

The base class must be initialized in the class header:

[source,kotlin]
----
abstract class Base

class Derived : Base() // Primary constructor is called
----

Alternatively, if the base class has no primary constructor, its secondary constructors can chain to ``super``:

[source,kotlin]
----
class Derived : Base {
    constructor() : super()
}
----

This ensures that the superclass constructor has finished by the time the subclass's initializers run.

TIP: Interfaces cannot be initialized in the class header because they do not have constructors.

==== ``abstract`` and ``override``

Functions and properties can also be ``abstract`` members of abstract classes and interfaces.
Interface functions are implicitly ``abstract``.
Default implementations for interface functions are easy to specify -- just give the function a body:

[source,kotlin]
----
interface Comparer<T1, T2> {
    fun compare(a: T1, b: T2): Boolean {
        return true // Default implementation always returns true
    }
}
----

To override a function or property, declare it in the subtype using the ``override`` modifier.

TIP: Unlike in Java, where ``Override`` is an annotation, ``override`` is a keyword in Kotlin.

To override a member and prevent further overriding, declare it as ``final``, like in C++:

[source,kotlin]
----
interface A {
    // `abstract` is implied, since this is an interface
    fun foo()
    val bar: String
}

open class B : A {
    final override fun foo()
    override val bar get() = "Baz"
}

class C : B {
    override fun foo() // ERROR
    override val bar get() = "Quux" // ok
}
----

TIP: ``override`` can even be used on primary constructor property parameters!
This is especially useful for use with data classes.

==== Explicit ``super``

If a class inherits the same member from multiple supertypes, it must provide its own implementation to avoid the diamond problem: footnote:[https://kotlinlang.org/docs/reference/classes.html#overriding-rules]

[source,kotlin]
----
open class Rectangle {
    open fun draw() { ... }
}

interface Polygon {
    fun draw() { ... } // Default implementation
}

class Square : Rectangle(), Polygon {
    // The compiler requires draw to be overridden:
    override fun draw() {
        super<Rectangle>.draw() // call to Rectangle.draw
        super<Polygon>.draw() // call to Polygon.draw
    }
}
----

==== Function objects

Kotlin treats functions as first-class language citizens; they can be stored in variables and passed around.
To accomplish this, Kotlin uses _function types_:

[source,kotlin]
----
val intConsumer: (Int) -> Unit = fun(int: Int) {
    println(int)
}
----

There is a shorter, more concise syntax for creating an anonymous function -- the _lambda expression_.

[source,kotlin]
----
val intConsumer: (Int) -> Unit = { int ->
    println(int)
}
----

Kotlin lambdas are entirely contained within ``{}``; like in Swift, the parameters are declared within the body itself:

[source]
----
{
    arg1, ... ->
    [lambda body]
    [last statement]
}
----

footnote:[This is largely paraphrased from my StackOverflow answer https://stackoverflow.com/a/45861598/7366707[here].]

The value of the last expression of a lambda is implicitly returned.

NOTE: If a lambda has only one parameter, the parameter list can be left out; the parameter receives the special name ``it``.

CAUTION: Avoid using implicit parameter names with nested lambdas -- it quickly becomes unclear just _which_ ``it`` is being referred to.

===== Lambdas as function parameters

Lambdas can be passed to functions as parameters.
There are many functions in the standard library which accept lambda expressions; most of their charm comes from the fact that _the last argument, if it is a lambda expression, can be placed outside of the function call_.

This might not sound like much at first, but this:

[source,kotlin]
----
val list = listOf(1, 2, 3)
list.forEach({
    println(it)
})
----

becomes

[source,kotlin]
----
val list = listOf(1, 2, 3)
list.forEach {
    println(it)
}
----

This is what helps many of Kotlin's standard library functions fit into the language so well --
they _look_ like they could be built-in language features, but they are really just normal, convenient functions.

A great example of this is https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/repeat.html[repeat]:

[source,kotlin]
----
// For loop
for (i in 0 until 7) {
    foo()
}

// `repeat`
repeat(7) {
    foo()
}
----

``repeat`` is much more readable, and the intent of the code becomes much clearer at no additional cost.

===== Inlining lambdas

Functions can be declared as ``inline`` -- this means that they will not be compiled to an actual function; their code will simply be pasted into the call site wherever it is used.
The usefulness of this feature becomes apparent when it is combined with lambdas.
Literal lambdas passed to inline methods will also become inlined:

[source,kotlin]
----
inline fun run(block: () -> Unit) {
    block()
}

run { println("Hello, world!") }
----

is compiled to simply

[source,kotlin]
----
println("Hello, world!")
----

This removes the entire object overhead of lambda expressions, and allows useful functional utilities to be built.

NOTE: Most standard-library functions that affect control flow (i.e. ``repeat``, ``forEach``, ``map``, etc.) are inlined and thus incur no performance penalties!

NOTE: If you need a lambda to remain in "object form" and not be inlined into an inline function (e.g. if you need to store it in a list), you can annotate the parameter as ``noinline``.

NOTE: If an inlined lambda needs to be cross-inlined into _another_ inline function (e.g. this inline function calls another one), you must annotate the parameter as ``crossinline``.

CAUTION: Because inline lambdas are inserted directly into the call site, ``return``ing from them may have unexpected behavior!

[source,kotlin]
----
fun loopList() {
    list.forEach { item ->
        if (item == 3) return // This will return from the ENTIRE function,
                              // not just from the lambda!
    }
}
----

This is called a non-local return, which is often seen in standard loops.
It is important to mean that ``return`` has no meaning within a lambda and always affects the enclosing function scope.
It is advisable to avoid using ``return`` within a lambda unless necessary.

====== ``reified`` generics

Inline functions can be used to provide compile-time reified generics.

Since the functions are inlined, they have access to generic type data:

[source,kotlin]
----
inline fun <reified T> checkType(any: Any): Boolean {
    return any is T // This would not work in Java,
                    // or in a non-inline function!
}
----

This allows ``is``, ``as``, and ``::class`` to be safely used on generic type parameters.

==== Anonymous objects

Objects of an anonymous type can be created using ``object`` literals.

[source,kotlin]
----
val runnable = object : Runnable {
    override fun run() {
        foo()
    }
}
----

However, when using SAM (single-abstract-method) interfaces that are defined in Java code, this is unnecessary, because Kotlin will automatically create helper constructors for these interfaces to allow for a nicer syntax.
This is called _SAM conversion_:

[source,kotlin]
----
val runnable = Runnable {
    foo()
}
----

Additionally, anonymous objects that do not extend any class can be created.
This is similar to C#'s ``new {}``.

[source,kotlin]
----
val list = listOf(3)
val mapped = list.map { int ->
    object {
        val value = int
    }
}

for (item in mapped) {
    println(item.value)
}
----

While the type cannot be referred to by name, it is available to the compiler and can thus be used within the same scope.
Since anonymous objects have no proper type, they cannot be returned from methods.

TIP: It is often better to use local data classes instead of untyped anonymous objects, as they are named and they more clearly express the intent of the code.

[source,kotlin]
----
fun foo() {
    data class TempData(...) // Local data class!
}
----
